### ISSUE TITLE
how to use stopKey to stop tomcatRun task

### ISSUE THREAD

**Issue by xfs** [bmuschko/gradle-tomcat-plugin#102]
now,in order to run tomcatRun task,i must kill the java process in task manager.
how to stop tomcatRun?
the tomcatStop task can not work. i passed debug config in the eclipse.

**Comment by bmuschko** [comment]
I am going to close this issue. It's not clear to me how your guys' setup looks like. Please reopen with the relevant information I requested. Two things to keep in mind:

* Gradle daemon != Tomcat plugin daemon
* Using the Gradle daemon will keep the Gradle process running the background and has nothing to do with the Tomcat plugin daemon flag.
