### ISSUE TITLE
howto: Use tomcatRun with no web.xml (WebApplicationInitializer)

### ISSUE THREAD

**Issue by davidlund** [bmuschko/gradle-tomcat-plugin#104]
Hi,

We trying to use tomcatRun on tomcat7 on a webapp that uses a WebApplicationInitializer and hence has no web.xml. This doesn't seem to work using tomcatRun but does work using tomcatRunWar - are we missing something. Heres the config we're using:

[tomcatRun,tomcatRunWar]*.contextPath="/"

**Comment by jadekler** [comment]
For the record, [this skeleton](https://github.com/jadekler/git-java-websiteskeleton/blob/master/applications/core/src/main/java/com/websiteskeleton/core/HelloInitializer.java#L12) uses `WebApplicationInitializer` and has no web.xml, and has no troubles with the tomcat gradle plugin.

**Comment by tdudgeon** [comment]
Just as a comment, I hit a quirk that I think is the same or related issue.
I create a very simple Servlet using only the @WebServlet annotation, and provide no web.xml.
When you run this using the `tomcatRunWar` task it works fine.
But if you run using the `tomcatRun` task the servlet is not reachable.
If I create an essentially empty web.xml then it now works OK.

**Comment by bmuschko** [comment]
Closing as issue got no traction.
