### ISSUE TITLE
Set redirectPort in SSL Connector

### ISSUE THREAD

**Issue by peter-backlund-sg** [bmuschko/gradle-tomcat-plugin#111]
Our web.xml protects all resources (/*) with transport-guarantee CONFIDENTIAL, and turning on SSL in the plugin works as expected. However, the redirectPort attribute seems to be set to 80, regardless of the value of the httpsPort attribute. My request is that this attribute is set to the value of httpsPort, probably in "BaseTomcat7xPlusImpl.configureHttpsConnector" (?).

Thank you.

**Comment by bmuschko** [comment]
Closing as issue got no traction.
