### ISSUE TITLE
PermGen Leak in AbstractTomcatRun Shutdown hook

### ISSUE THREAD

**Issue by rwinch** [bmuschko/gradle-tomcat-plugin#113]
[AbstractTomcatRun registers a shutdown hook](https://github.com/bmuschko/gradle-tomcat-plugin/blob/bf327ff7e4eec924c644791afe08cf4448ce47ab/plugin/src/main/groovy/com/bmuschko/gradle/tomcat/tasks/AbstractTomcatRun.groovy#L395) which causes the Tomcat Server's ClassLoader to be leaked since the System's ApplicationShutdownHooks has a reference to the server member. This causes an `OutOfMemoryError: PermGen space` when spawning many Tomcat instances in the same build.

Below is a YourKit Snapshot Screenshot of the issue

![image](https://cloud.githubusercontent.com/assets/362503/5349645/951b2a7e-7f00-11e4-9838-3bb3ca846c5a.png)

Unfortunately I cannot upload the dump to github issues because it is too large. For reference, the build is [Spring Security's integration tests](https://github.com/spring-projects/spring-security).

To resolve this, the Tomcat plugin should probably not register a Shutdown Hook with the JVM. Instead, shutting it down should be done by Gradle's APIs.

**Comment by rwinch** [comment]
Rather than adding a shutdown hook in AbstractTomcatRun, shutdown could be invoked in a finalizedBy.

**Comment by bmuschko** [comment]
@rwinch I'd like to revive this topic. Would you be interested in looking deeper into this issue? I'd be OK with removing the shutdown hook but would also want to make sure that the Gradle daemon process doesn't keep holding on to other instances of Tomcat servers.

**Comment by rwinch** [comment]
@bmuschko Thanks for the response. Unfortunately I have extremely limited time for the next month or so. However, I would be willing to dig in at that point.

> I'd be OK with removing the shutdown hook but would also want to make sure that the Gradle daemon process doesn't keep holding on to other instances of Tomcat servers.

The daemon is actually another example of why the memory leak is an issue. Because the JVM is never shutdown, it holds on to the shutdown hook which means memory is leaked. 

Perhaps an even better solution is to ensure the shutdown hook gets removed. For example see [rwinch/gh113](https://github.com/bmuschko/gradle-tomcat-plugin/compare/master...rwinch:gh113?expand=1).

**PS**: Please forgive the crudeness (i.e. no test, whitespace changes in the commit, not real PR) as the choice for me at the moment is crude or not responding. At one point one of the tests failed with an error message being incorrect (i.e. it contained XML instead of TLD or something like that). It doesn't appear to happen anymore, but I haven't had time to look into it. 

# Additional Notes

It appears there are additional memory related problems. I created a [sample project](https://github.com/rwinch/gradle-tomcat-plugin-permgen) to demonstrate them. I think some of the issues might be with Gradle itself.

Even with such a small footprint (i.e. no jars within the sample application) it causes the JVM to crash after about permGen50 runs. If the application were larger (had more jars that were loaded), it is quite likely this would happen much faster.

I haven't had time to look into why it runs out of memory, but it seems if I run the task once, I should be able to run it as many times as I want (assuming I am certain the other tasks are completed and can be GCd) without causing the JVM to crash.

**Comment by bmuschko** [comment]
> Thanks for the response. Unfortunately I have extremely limited time for the next month or so. However, I would be willing to dig in at that point.

Same here. ;-)

> Perhaps an even better solution is to ensure the shutdown hook gets removed. For example see rwinch/gh113.

I'd be happy to incorporate that. Did you do some memory profiling with that fix to verify it improves the situation?

> It appears there are additional memory related problems. I created a sample project to demonstrate them. I think some of the issues might be with Gradle itself.

The daemon is known to still have memory leaks. It's one of the reasons it's not turned on by default and why it has the incubating status.

> I haven't had time to look into why it runs out of memory, but it seems if I run the task once, I should be able to run it as many times as I want (assuming I am certain the other tasks are completed and can be GCd) without causing the JVM to crash.

There's the possibility of the plugin leaking objects as well. I'd need to spend some time on it with YourKit. Anybody else that wants to step in to help out is welcome!

**Comment by rwinch** [comment]
@bmuschko Thank you for your reply.

> I'd be happy to incorporate that. Did you do some memory profiling with that fix to verify it improves the situation?

I was able to confirm (profiling with YourKit) that the commit I provided improves the situation. I went ahead and created an official PR #123 to make merging as easy as possible. Once again, sorry for the very poor PR w/ no tests, whitespace changes, etc.

Hopefully next month I will get a chance to look into some of the other memory issues I am coming across. It is even possible the problems are on my side (i.e. with my sample) since I couldn't dig into the problem much.

**Comment by bmuschko** [comment]
> I was able to confirm (profiling with YourKit) that the commit I provided improves the situation.

Thanks for that!

> Hopefully next month I will get a chance to look into some of the other memory issues I am coming across.

Great, I am looking forward to more findings.
