### ISSUE TITLE
release org.gradle.api.plugins:gradle-tomcat-plugin:2.0 in maven repository

### ISSUE THREAD

**Issue by egaga** [bmuschko/gradle-tomcat-plugin#118]
The most recent versions of the gradle-tomcat-plugin are not available through maven central. How come?

**Comment by egaga** [comment]
jcenter has it.

**Comment by bmuschko** [comment]
You can also find the [latest version](http://search.maven.org/#browse%7C38272645) of the plugin on Maven Central. Please note that the `groupId` has changed.
