### ISSUE TITLE
How to configure tomcat logging level

### ISSUE THREAD

**Issue by Andy-L** [bmuschko/gradle-tomcat-plugin#122]
I'd like to configure tomcat's logging level when using `tomcatRunWar`, but I don't see any way to do that.  Can I drop a `logging.properties` or `log4j.properties` file somewhere, or is there another way to set tomcat's logging level?

**Comment by bmuschko** [comment]
At the moment you can't. It would have to be exposed. Would you be interested in contributing this feature?

**Comment by bmuschko** [comment]
Looking at this again. I actually did put something in place - `com.bmuschko.gradle.tomcat.internal.LoggingHandler`. At the moment it's just not configurable.

**Comment by jadekler** [comment]
Seconded - this would be huuuuugely helpful for our team. Is there a way around this in the meantime? We are not tomcat experts and are having trouble finding a way around the enormous mass of debug output atm.

**Comment by jonatasschagas** [comment]
In my case I've run gradle providing the following parameter:
```
gradle tomcatRun -Dlog4j.configurationFile=src/main/resources.log4j.properties
```
Not optimal but it does the trick for me

**Comment by jadekler** [comment]
We ended up doing something similar (providing a log4j on the classpath of our app).

**Comment by MohdAlomar** [comment]
I tried to use 

`gradle tomcatRun -Dlog4j.configurationFile=src/main/resources.log4j.properties`

but it didn't work I am using tomcat version 7.0.59 is it possible to post the configuration file here ?

**Comment by bmuschko** [comment]
@Koli0842 Nothing happened here in the meantime. Happy to accept pull requests for this.

**Comment by mhuebner** [comment]
I managed to workaround this issue by configuring web.xml (works for `tomcatRun` and `tomcatRunWar` tasks) for an old (really old) Spring 2.5/Gradle 5.6.2 app:

```
<listener>
	<listener-class>org.springframework.web.util.Log4jConfigListener</listener-class>
</listener>

<context-param>
	<param-name>log4jExposeWebAppRoot</param-name>
	<param-value>false</param-value>
</context-param>

<context-param>
	<param-name>log4jConfigLocation</param-name>
	<param-value>classpath:log4j.properties</param-value>
</context-param>
```

**Comment by bmuschko** [comment]
Seems like a solution has been provided with the last comment.
