### ISSUE TITLE
System Properties (feature request)

### ISSUE THREAD

**Issue by gnomff** [bmuschko/gradle-tomcat-plugin#126]
Hi,

I would like to be able to set system properties in the tomcatRun task. In the application plugin you can do something like:

`run {    
    systemProperties System.getProperties()
}`

or
`applicationDefaultJvmArgs = ["-Dgreeting.language=en"]`  

I would like to be able to do the same thing with tomcatRun

**Comment by bmuschko** [comment]
See README of the plugin:

> Gradle starts the embedded container in the same JVM. Currently, the container cannot be forked as a separate process.

Consequently, system properties would have to be provided to the Gradle process.

**Comment by gnomff** [comment]
Oh, I didn't see that - thanks!
