### ISSUE TITLE
Adding to the tomcat lib dir

### ISSUE THREAD

**Issue by tdudgeon** [bmuschko/gradle-tomcat-plugin#127]
I need to add jars to the tomcat lib directory.
Is this what the additionalRuntimeResources property does?
Ideally to populate this from Maven coordinates.

**Comment by bmuschko** [comment]
Correct, that's the purpose of the property. It's very easy to assign the files pulled from a configuration to that property. Just declare your dependency with a custom configuration. Access the files of the configuration and assign it to the property. The dependencies can come from any repository. It depends on what repositories you declare in your `repositories` block.

BTW: Let me know if the description of the property in the `README` file doesn't properly express its intend. I'd like to improve it if it's not clear.

**Comment by tdudgeon** [comment]
Thanks. The only thing that wasn't clear to me was whether the additionalRuntimeResources property resulted in the specified files being added to the tomcat lib dir. I assumed it was, and it might be worth specifically stating this.

**Comment by bmuschko** [comment]
OK, thanks for the feedback. In fact for the embedded implementation of Tomcat there really is no `lib` directory. It's being put together in memory.
