### ISSUE TITLE
Slowness of TomcatRun

### ISSUE THREAD

**Issue by ferzerkerx** [bmuschko/gradle-tomcat-plugin#131]
Hi

I'm switching from maven to gradle and trying to setup the tomcat plugin for gradle and I've noticed that starting tomcat using the plugin with my current config is slower than maven's

buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.bmuschko:gradle-tomcat-plugin:2.2.2"
    }
}

apply plugin: "com.bmuschko.tomcat"

dependencies {
    def tomcatVersion = '7.0.59'
    tomcat "org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}",
            "org.apache.tomcat.embed:tomcat-embed-logging-juli:${tomcatVersion}",
            "org.apache.tomcat.embed:tomcat-embed-jasper:${tomcatVersion}"
}
tomcat {
    httpPort = 8080
    httpsPort = 8091
    enableSSL = false
//    TODO SSL setup
    contextPath = '/'
}

tomcatRun {
    doFirst {
        System.setProperty("networkaddress.cache.ttl", 'networkaddress.cache.ttl')
        System.setProperty("java.net.preferIPv4Stack", 'true')
        System.setProperty("tc.active", 'true')
        System.setProperty("org.gradle.jvmargs", '-Xms3G -Xmx3G -XX:PermSize=256M -XX:MaxPermSize=256m -verbose:gc')
    }
    daemon = true

    configFile = file('' + projectDir + '/src/main/webapp/META-INF/context-dev.xml')
    additionalRuntimeResources << file('' + projectDir + '/../client-assets/client')
    additionalRuntimeResources << file('' + projectDir + '/../components')
}

war {
    zip64 = true
}

uncompressed war stands at ~200MB

found a related post on http://www.reddit.com/r/java/comments/22rb8z/gradle_build_process_is_painfully_slow/ but didn't find any resolution.

Any ideas?

**Comment by bmuschko** [comment]
This is very likely unrelated to the plugin itself. It's more the fact that Gradle has a slower startup time than Gradle. There are definitely a bunch of things you can do to improve the startup time e.g. use the daemon. Future versions of Gradle will bring down the startup time significantly.

I am going to close the issue here. I'd recommend you open a discussion on the Gradle forum.
