### ISSUE TITLE
TomcatStop doesn't wait for stop

### ISSUE THREAD

**Issue by bjkail** [bmuschko/gradle-tomcat-plugin#136]
TomcatStop does not actually wait for the server to stop.  You can observe this by adding a ServletContextListener with a contextDestroyed, and you'll see that it runs in parallel to the rest of the build.  We've worked around this locally with a TomcatStop subclass that calls s.inputStream.read() to wait for ShutdownMonitor to close its socket first, which happens after server.stop returns:

    class CustomTomcatStop extends com.bmuschko.gradle.tomcat.tasks.TomcatStop {
        // The method body is a copy of TomcatStop.stop except where noted.
        @Override
        void stop() {
            if(!getStopPort()) {
                throw new InvalidUserDataException('Please specify a valid port')
            }
            if(!getStopKey()) {
                throw new InvalidUserDataException('Please specify a valid stopKey')
            }
    
            try {
                Socket s = new Socket(InetAddress.getByName('127.0.0.1'), getStopPort())
                s.setSoLinger(false, 0)
    
                OutputStream out = s.outputStream
                out.write((getStopKey() + '\r\nstop\r\n').bytes)
                out.flush()
    
                // BEGIN FIX
                // Wait for the socket to be closed after the server is stopped.  No
                // response is actually written, so this always returns -1.
                s.inputStream.read()
                // END FIX
    
                s.close()
            }
            catch(ConnectException e) {
                logger.info 'Tomcat not running!'
            }
            catch(Exception e) {
                logger.error 'Exception during stopping', e
            }
        }
    }

Without this, we have also observed spurious exceptions due to a race condition between ShutdownMonitor and the TomcatRunWar shutdown hook attempting to stop the server simultaneously.  It appears there is missing synchronization, and both code paths can attempt to stop the server.

**Comment by bmuschko** [comment]
@bjkail Would you be interested in creating a pull request for this? That'll make it easier to get it integrated.
