### ISSUE TITLE
the tomcat localhost.log is missing

### ISSUE THREAD

**Issue by rlagoue** [bmuschko/gradle-tomcat-plugin#139]
Hello,

it seems like the file localhost.xxxxx.log is somehow removed by the cargo plugin, is it a bug or a feature?

Not having it may cause someone spends hours guessing what could be wrong when the application remains inaccessible after tomcat start. Since no stacktraces are printed in the file catalina.out in this case.

Thank you

**Comment by bmuschko** [comment]
Can you explain this a little bit in more detail? I can't quite follow. So you are using the Cargo plugin _and_ the Tomcat plugin in the same project? If yes, please post your configuration. When do you see the log file being removed? By which plugin is the log file created?

**Comment by bmuschko** [comment]
Closing the issue. Not response by the reporter of the issue.

**Comment by rlagoue** [comment]
Sorry I was not notified about your answer. 
Here are my configurations 
`cargo {
	containerId =  "${rootProject.cargoContainerId}"
	local {
		homeDir 	= file(cargoHome)
		configHomeDir 	= file(cargoHome)
		outputFile = file('build/containerOutput.log')
		logFile = file('build/containerOutput.log')
		logLevel = 'low'
		sharedClasspath = files(configurations.postgresJdbc.resolvedConfiguration.resolvedArtifacts*.file)
		...`

The problem is that unexpected exceptions stacktrace are not printed out in any cargo output log files. When I use the war generated by my application during the gradle build in a normal tomcat installation, I can see the stack trace in the file <TOMCAT_HOME>/logs/localhost.<timestamp>.log

It is a little bit annoying since I have to check it  in a normal tomcat installation everytime I get into troubles

Thank you
