### ISSUE TITLE
reopening of https://github.com/bmuschko/gradle-tomcat-plugin/issues/139

### ISSUE THREAD

**Issue by rlagoue** [bmuschko/gradle-tomcat-plugin#143]
Hi,

I would like to reopen the issue https://github.com/bmuschko/gradle-tomcat-plugin/issues/139. I have added a comment there.

How may I reopen this.

Thank you

**Comment by bmuschko** [comment]
The issue you are raising is for the [Gradle Cargo plugin](https://github.com/bmuschko/gradle-cargo-plugin) and not related to the Tomcat plugin. Please raise the issue there.

**Comment by rlagoue** [comment]
ok
