### ISSUE TITLE
how do I  add  catalina .properties  use  tomcat  plugin in gradle

### ISSUE THREAD

**Issue by pankui** [bmuschko/gradle-tomcat-plugin#146]
I try to configure:
tomcatRun.configFile = file('src/main/webapp/META-INF/context.xml')

or

[tomcatRun, tomcatRunWar]*.configFile = file('src/main/webapp/META-INF/catalina.properties') 

but  tomcatRun:

Parse Fatal Error at line 1 column 1: Preface content not allowed。
org.xml.sax.SAXParseException; systemId: file:/D:/workspace/Survey2016/src/main/
webapp/META-INF/catalina.properties; lineNumber: 1; columnNumber: 1; Preface content not allowed

**Comment by pankui** [comment]
I need configure 
org.apache.jasper.compiler.Parser.STRICT_QUOTE_ESCAPING=false

**Comment by bmuschko** [comment]
The property is only supported with Tomcat 7.x and earlier. For 8.x and up you need to configure the  parameter in the `web.xml`: http://stackoverflow.com/questions/19421587/strict-quote-escaping-in-tomcat. Parsing a `catalina.properties` is not supported by this plugin. It is not using a standalone Tomcat installation in that sense.
