### ISSUE TITLE
Way to instantiate tomcat with custom war task

### ISSUE THREAD

**Issue by SeatherMarqx0** [bmuschko/gradle-tomcat-plugin#149]
I have a fairly complicated project with multiple war files. Each war file is dependant on the same core source code.

To generate the war files,  I created some of my own war tasks. Is there a way to instantiate the tomcat plugin with each of the war files? As in, can I create several tomcat tasks with individual war tasks?

Thanks,
Will

**Comment by bmuschko** [comment]
Yes, it's possible. That the purpose of the `com.bmuschko.tomcat-base` plugin. [This test case](https://github.com/bmuschko/gradle-tomcat-plugin/blob/master/plugin/src/functTest/groovy/com/bmuschko/gradle/tomcat/TomcatBasePluginFunctionalTest.groovy) demonstrates how to set it up. In addition you will need to assign the web application classpath to the property exposed by the relevant custom task.

**Comment by bmuschko** [comment]
Closing the issue. Let me know if you need additional information.
