### ISSUE TITLE
idea socket closet

### ISSUE THREAD

**Issue by libra1010** [bmuschko/gradle-tomcat-plugin#151]
my system is windows10 
configure idea remote and gradle
buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.bmuschko:gradle-tomcat-plugin:2.2.5'
    }
}

 def tomcatVersion = '8.5.9'
    tomcat   "org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}",
            "org.apache.tomcat.embed:tomcat-embed-logging-juli:${tomcatVersion}",
            "org.apache.tomcat.embed:tomcat-embed-jasper:${tomcatVersion}"

TomcatRun and TomcatRunWar All tips "socket closed"

**Comment by bmuschko** [comment]
Sorry, I do not understand the question you have. Can you elaborate?

**Comment by bmuschko** [comment]
I am going to close the issue as I haven't received additional feedback. Feel free to reopen the issue if you can provide more information.
