### ISSUE TITLE
Up to date checking not supported on tomcatJasper task

### ISSUE THREAD

**Issue by scottresnik** [bmuschko/gradle-tomcat-plugin#158]
Hello:

I noticed that Gradle's up to date checking is [explicitly overridden](https://github.com/bmuschko/gradle-tomcat-plugin/blob/master/plugin/src/main/groovy/com/bmuschko/gradle/tomcat/tasks/Tomcat.groovy#L31).

Could you share some background on why this was done?

**Comment by bmuschko** [comment]
There are usually two use cases:

- You want to manually test changes in a Tomcat instance. A user wants to start to container even if the configuration for Tomcat didn't change in the meantime. There's no point for it to be up to date.
- You use a Tomcat container for integration testing. To be able to run the tests you will need to have a running container. The only use where you might want this to be up to date is if the tests didn't change and were executed before. However, in those cases [a more powerful concept on the Gradle level is required](https://github.com/gradle/gradle/issues/1414).

What use case are you thinking of where it would make sense for Tomcat to be up to date?

**Comment by scottresnik** [comment]
The use case I was thinking of is precompiling JSP pages using the tomcatJasper task.  I would like the compilation to be avoided if the JSP files have not changed.

**Comment by bmuschko** [comment]
OK, thanks. That's a valid use case. We should [decouple that logic](https://github.com/bmuschko/gradle-tomcat-plugin/blob/master/plugin/src/main/groovy/com/bmuschko/gradle/tomcat/tasks/TomcatJasper.groovy#L26) from the `TomcatJasper` task. I guess we could move the `upToDate` logic into a subtype that is only used by the task types that start the server.

**Comment by scottresnik** [comment]
That is exactly what I was thinking as well.
