### ISSUE TITLE
war overlay compatibility

### ISSUE THREAD

**Issue by mandrachek** [bmuschko/gradle-tomcat-plugin#164]
This plugin works fine with the war overlay plugin (https://github.com/scalding/gradle-waroverlay-plugin) when using the tomcatRunWar task, but the tomcatRun task doesn't seem to work - it doesn't include resources needed from the overlay wars.  It would be great if these two could work together, or if anyone knows a workaround. I posted a similar question on their tracker - https://github.com/scalding/gradle-waroverlay-plugin/issues/10

**Comment by bmuschko** [comment]
The task `tomcatRun` never builds a WAR file. That's on purpose and for performance reasons. You'll have to stick with the `tomcatRunWar` if you need WAR overlays in any form.
