### ISSUE TITLE
precompile jsp doesn't catch ${}

### ISSUE THREAD

**Issue by freshcodemonger** [bmuschko/gradle-tomcat-plugin#166]
jsp precompile doesn't detect an error with ${} syntax but if you render the jsp servlet it reports an error. Is this a precompile issue with tomcat or with the plugin?  

Thank you !

buildscript {  
    repositories {  
        jcenter()  
    }  
  
  
    dependencies {  
        classpath 'com.bmuschko:gradle-tomcat-plugin:2.3'  
    }  
}  

apply plugin: com.bmuschko.gradle.tomcat.TomcatPlugin 
apply plugin: 'java'

dependencies {
   def tomcatVersion = '8.5.13'
   def tomcatJuli = '8.5.2'  
        tomcat "org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}",  
               "org.apache.tomcat.embed:tomcat-embed-logging-juli:${tomcatJuli}",  
               "org.apache.tomcat.embed:tomcat-embed-jasper:${tomcatVersion}",  

...

**Comment by freshcodemonger** [comment]
This is the runtime error I get - I am guessing this is a tomcat jsp precompile enhancement that is needed and not something in the gradle plugin that uses it?

Failed to parse the expression [${}] Encountered " "}" "} "" at line 1, column 3.
Was expecting one of:
"{" ...
<INTEGER_LITERAL> ...
<FLOATING_POINT_LITERAL> ...
<STRING_LITERAL> ...
"true" ...
"false" ...
"null" ...
"(" ...
"[" ...
"!" ...
"not" ...
"empty" ...
"-" ...
<IDENTIFIER> ...
<IDENTIFIER> ...
"(" ...

**Comment by bmuschko** [comment]
The plugin only passes on configurable properties to the Ant task provided by the Tomcat project. The Jasper Gradle task doesn't implement any custom logic on top of it. So if you see failures then they'll very likely come from the Tomcat implementation. My guess is that the Jasper compiler does not properly detect the syntax error up front.

You might be able to tweak some of the behavior with the exposed properties. For example:

[quoteAttributeEL](https://tomcat.apache.org/tomcat-8.0-doc/jasper-howto.html) - When EL is used in an attribute value on a JSP page, should the rules for quoting of attributes described in JSP.1.6 be applied to the expression? true or false, default true.

It's probably best if you'd check with the Tomcat project.

**Comment by bmuschko** [comment]
I am going to close this issue as I haven't heard back from you. Pretty sure this is not an issue with the plugin.

**Comment by freshcodemonger** [comment]
I logged a bug for the jasper project - it has been fixed in the trunk.  Thanks for the plugin !!

https://bz.apache.org/bugzilla/show_bug.cgi?id=61816
