### ISSUE TITLE
Gradle 4 warning: Gradle now uses separate output directories for each JVM language...

### ISSUE THREAD

**Issue by xingxiuyi** [bmuschko/gradle-tomcat-plugin#168]
Run with gradle-tomcat-plugin, gradle warning: 

Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0

in this file: plugin/src/main/groovy/com/bmuschko/gradle/tomcat/tasks/TomcatRun.groovy

method: 

```
private void setupClassesJarScanning() {
    ....
    File resolvedClassesDirectory = getClassesDirectory()
    ....
}

```

CALL getClassesDirectory() will print those warning.

**Comment by bmuschko** [comment]
Thanks for the reminder. Would you be interested in providing a pull request for this?
