### ISSUE TITLE
tomcatJasper does not support the option strictQuoteEscaping as Jasper has

### ISSUE THREAD

**Issue by luyentran** [bmuschko/gradle-tomcat-plugin#177]
tomcatJasper does not support the option strictQuoteEscaping as Jasper has.
Not able to set the strictQuoteEscaping to false when running the task tomcatJasper

**Comment by bmuschko** [comment]
Looks like an option that came in with a later version of Tomcat. Please provide a pull request if you'd like to expose a property and pass on the flag to the Ant Jasper task.

- Should add an integration test that verifies its proper working.
- Should verify the behavior for Tomcat versions that do not support the option.
- Should add Javadocs.

**Comment by bmuschko** [comment]
Closing as issue got no traction.
