### ISSUE TITLE
How to config gradle-tomcat-plugin in build.gradle.kts (Kotlin DSL)

### ISSUE THREAD

**Issue by ms143014** [bmuschko/gradle-tomcat-plugin#178]
repositories {
    mavenCentral()
}

dependencies {
    def tomcatVersion = '8.5.16'
    tomcat "org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}",
           "org.apache.tomcat.embed:tomcat-embed-logging-juli:8.5.2",
           "org.apache.tomcat.embed:tomcat-embed-jasper:${tomcatVersion}"
}

tomcat {
    httpProtocol = 'org.apache.coyote.http11.Http11Nio2Protocol'
    ajpProtocol  = 'org.apache.coyote.ajp.AjpNio2Protocol'
}
//-----------------------------
//How to config gradle-tomcat-plugin in build.gradle.kts?

**Comment by bmuschko** [comment]
Something like this should do:

```
import com.bmuschko.gradle.tomcat.extension.TomcatPluginExtension

plugins {
    java
    id("com.bmuschko.tomcat") version "2.5"
}

repositories {
    mavenCentral()
}

dependencies {
    tomcat("org.apache.tomcat.embed:tomcat-embed-core:8.5.16")
    tomcat("org.apache.tomcat.embed:tomcat-embed-logging-juli:8.5.2")
    tomcat("org.apache.tomcat.embed:tomcat-embed-jasper:8.5.16")
}

configure<TomcatPluginExtension> {
    httpProtocol = "org.apache.coyote.http11.Http11Nio2Protocol"
    ajpProtocol = "org.apache.coyote.ajp.AjpNio2Protocol"
}
```

**Comment by bmuschko** [comment]
I am going to close this issue for now. Let me know if you have more questions.
