### ISSUE TITLE
Support for any `web.xml` location

### ISSUE THREAD

**Issue by lapo-luchini** [bmuschko/gradle-tomcat-plugin#179]
[It seems to me](https://github.com/bmuschko/gradle-tomcat-plugin/blob/8612a94fe3f41ffa9dae2051aeeb281fd2b3cdfd/plugin/src/main/groovy/com/bmuschko/gradle/tomcat/tasks/TomcatRun.groovy#L115) that `web.xml` is always searched for in `uriroot/WEB-INF/web.xml` while it could be defined elsewhere, e.g. I'm using:

```Groovy
war {
    webInf { from 'etc' }
    from('WebContent')
}
```

Would it be possible to support that?
(if it is already, sorry, but I couldn't find it)

**Comment by bmuschko** [comment]
At the moment the plugin only uses the [conventional directory from the War Plugin](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.WarPluginConvention.html#org.gradle.api.plugins.WarPluginConvention:webAppDir). That is [org.gradle.api.plugins.WarPluginConvention:webAppDir](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.WarPluginConvention.html#org.gradle.api.plugins.WarPluginConvention:webAppDir). Your proposal would only work if you'd run the task `tomcatRunWar`. The task `tomcatRun` doesn't even build a WAR file. It simply points to directories. Did you run the task `tomcatRunWar`?

**Comment by lapo-luchini** [comment]
Sorry I forgot parts of my question: I'm using `tomcatJasper` as I only need to "test" my JSPs, I don't deploy from gradle (up to today, at least).

In the meantime I also tried calling JspC directly from ant… and it's the same, so I guess the limit is really [Jasper](http://grepcode.com/file/repo1.maven.org/maven2/org.apache.tomcat/tomcat-jasper/8.0.24/org/apache/jasper/JspC.java#1050) and not this plugin, really. :-/

**Comment by bmuschko** [comment]
You could try to set `validateXml` to `false` and see if that ignores your `web.xml`. I guess you don't want to verify the `web.xml`? At the moment `validateXml` is not exposed by the task.

**Comment by lapo-luchini** [comment]
Yes, doesn't really need the XML per se, problem is, it needs to use the correct directory because there are TLDs in a subdirectory.
In the end I solved it using a copy task to put `*.jsp` and `WEB-INF` in the expected positions.
