### ISSUE TITLE
Correct JNDI dbcp artifact url in documentation

### ISSUE THREAD

**Issue by shafinmahmud** [bmuschko/gradle-tomcat-plugin#180]
Mentioned dbcp url (`tomcat "org.apache.tomcat:dbcp:${tomcatVersion}"`) in the section **My Tomcat container needs to use a JNDI datasource. How do I set up my project?** is wrong. This needs to be corrected to  `tomcat "org.apache.tomcat:tomcat-dbcp:${tomcatVersion}"`

**Comment by bmuschko** [comment]
That was still the case for [Tomcat 6.x](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.apache.tomcat%22%20AND%20a%3A%22dbcp%22). The Apache project changed the coordinates starting with [version 7.x](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.apache.tomcat%22%20AND%20a%3A%22tomcat-dbcp%22). I added more detailed information with [this commit](https://github.com/bmuschko/gradle-tomcat-plugin/commit/477325959ebffb0e55c3312f2cb34e97fa398de2).

**Comment by shafinmahmud** [comment]
Okay, Its nicer now.
