### ISSUE TITLE
how to config tomcat Virtual Directories?

### ISSUE THREAD

**Issue by wufangit** [bmuschko/gradle-tomcat-plugin#182]

**Comment by bmuschko** [comment]
You'd have to provide a Tomcat config file and set it in the extension. You can find a test case demonstrating the use case here: https://github.com/bmuschko/gradle-tomcat-plugin/blob/master/plugin/src/functTest/groovy/com/bmuschko/gradle/tomcat/TomcatPluginFunctionalTest.groovy#L295-L328
