### ISSUE TITLE
Tomcat 8.5 Plugin Could not find property 'classesDirs' 

### ISSUE THREAD

**Issue by cdx-grillo** [bmuschko/gradle-tomcat-plugin#184]
Hello, 
I attempted to upgrade from ~tomcat-plugin~  tomcat version 8.0.39 to 8.5.16 and I'm seeing this error 
>"Could not determine the dependencies of task ':msite_portal:tomcatRun'.
Could not find property 'classesDirs' on main output."

I saw older posts about this from a few years back but the solutions didn't work for me; also seemed like the problem was resolved on subsequent releases. I didn't see this issue on the tomcat 8.0.39 version.   I simply changed the dependencies object to grab gradle-tomcat-plugin:2.5 and then updated the tomcatVersion to 8.5.16.

**Comment by bmuschko** [comment]
This is very likely happening because you use a somewhat [outdated version of Gradle](https://github.com/bmuschko/gradle-tomcat-plugin/issues/168). What version are you using? Try to upgrade to latest plugin version and the latest Gradle version.

There's no 8.5.16 plugin version. I guess you are referring to the Tomcat version?

**Comment by cdx-grillo** [comment]
Thanks very much for the reply.  I was using an older version of gradle (2.13) so I upgraded to 4.10 which is close to the latest.  For the plugin, in summary, I'm using: 
>    dependencies {
        classpath 'com.bmuschko:gradle-tomcat-plugin:2.5'
    }
>apply plugin: 'com.bmuschko.tomcat' 
...
>dependencies {
    def tomcatVersion = '8.5.16'
    tomcat ...
}

Unfortunately, still seeing the "Could not find property 'classesDirs' on main output." error  when invoking gradle tomcatRun

**Comment by bmuschko** [comment]
Could you please provide a reproducible example as a GitHub repository? Please also make sure to check in the wrapper files.

**Comment by cdx-grillo** [comment]
Figured it out, the tomcat 8.5.16 is working now.  It was your comment: 
>Please also make sure to check in the wrapper files.

I was using the gradle wrapper and the wrapper properties file has this hard-coded: 
>distributionUrl=https\://services.gradle.org/distributions/gradle-2.3-all.zip

So, even though I upgraded gradle to 4.10, it was still using 2.3 via the wrapper.  Apologies, user error. Thanks for your help on this, really appreciate it!
