### ISSUE TITLE
Daemon does not stop

### ISSUE THREAD

**Issue by seibu** [bmuschko/gradle-tomcat-plugin#185]
I got the following issue.

Using Gradle 5.2.1 and the following config

<pre>plugins {
    id 'war'
    id 'com.bmuschko.tomcat' version '2.5'
}

group 'de.seibushin'
version '1.0'

repositories {
    mavenCentral()
}

dependencies {
    compile 'ch.qos.logback:logback-classic:1.0.13'
    compile 'com.h2database:h2:1.4.197'
    compile 'org.hibernate:hibernate-core:5.4.1.Final'
    compile 'javax.servlet:jstl:1.2'

    providedCompile 'javax.servlet:javax.servlet-api:3.1.0'

    tomcat 'org.apache.tomcat.embed:tomcat-embed-core:9.0.16'
    tomcat 'org.apache.tomcat.embed:tomcat-embed-jasper:9.0.16'
}

tomcat {
    httpProtocol = 'org.apache.coyote.http11.Http11Nio2Protocol'
    ajpProtocol = 'org.apache.coyote.ajp.AjpNio2Protocol'
}</pre>

I start the server using ./gradlew tomcatStart and everything works as expected. When i want to shut down the server i use ./gradlew tomcatStop
The tomcatStop task finishes successful and i get the responding log from the servletContextListener about in contextDestroyed().
But the daemon which started the task tomcatRun is still running, so the build actually never finishes even if i explicitly stop the server which should result in the tomcatRun to stop i would think

Thanks!

Hope you can help me with this.

**Comment by bmuschko** [comment]
Are you asking about the Gradle daemon process? That one will never go away and is not controlled by this plugin.

**Comment by seibu** [comment]
Ok so if i want to start and stop the server using gradle, what is the correct way? Or otherwise how do i stop the gradle daemon after the server is stopped? ctrl+c does not work here. Do i rly have to kill it seperately?

Thanks for your answer!

**Comment by bmuschko** [comment]
Just to clarify: The [Gradle daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html) has really nothing to do with the functionality of this plugin. It's a general Gradle functionality enabled by default. It's purpose is to improve build execution performance by running Gradle in a background process.

If you do not want to use the daemon then you can disable it though my question would be why?

**Comment by seibu** [comment]
Ah thanks for clarifiing. I definitely mixed some things up.
