### ISSUE TITLE
Define which war to use

### ISSUE THREAD

**Issue by edimusrex** [bmuschko/gradle-tomcat-plugin#186]
My project has a fairly complex build process so I would like to be able to have the tomcat plugin choose the war that is built from my task instead of a standard WAR build process.  Can this be done?

**Comment by bmuschko** [comment]
You should be able to set the WAR file via the following:

```
tasks.withType(TomcatRunWar) {
    webApp = <your-war-file>
}
```

**Comment by edimusrex** [comment]
Adding the above throws the following error

> A problem occurred evaluating root project 'iC'.
> Could not find method withType() for arguments [task ':tomcatRunWar', build_8a9r4tsfqjq9meq9akmu6803e$_run_closure28@11e80ef] on task set of type org.gradle.api.internal.tasks.DefaultTaskContainer.

I have it written as so

    tasks.withType(tomcatRunWar){
        dependsOn 'build_notest'
        webApp = 'build/dist/iC.war'
    }

**Comment by bmuschko** [comment]
It's unlikely that your code worked as you posted it here. The [method `withType`](https://docs.gradle.org/current/javadoc/org/gradle/api/DomainObjectCollection.html#withType-java.lang.Class-) takes a `Class`. `tomcatRunWar` is an instance of `Task` and not a `Class` instance.

**Comment by edimusrex** [comment]
I'm sorry, I am a little confused with your answer.  Above you said it would work and then you said it wouldn't?  Could you please clarify?  Thank you

**Comment by bmuschko** [comment]
I think I misread your answer. You stated that it doesn't work for you because of error x. I thought you had said that it did work. Sorry, no coffee yet.

I removed the first sentence in my answer. It should make more sense now.

**Comment by edimusrex** [comment]
I am with you on that.  Changing the code to 
 
    tomcatRunWar {
        dependsOn 'build_notest'
        webApp = 'build/dist/iC.war'
    }

Throws the following error

> A problem occurred evaluating root project 'iC'.
> Cannot cast object 'build/dist/iC.war' with class 'java.lang.String' to class 'java.io.File'

The other method throws the previous error I listed.  

Thanks for the help

**Comment by bmuschko** [comment]
The field `webApp` is of type `java.io.File` so you'll have to assign the right type (see the [Javadocs of the task type](http://bmuschko.github.io/gradle-tomcat-plugin/docs/groovydoc/com/bmuschko/gradle/tomcat/tasks/TomcatRunWar.html#webApp)).

It would have to look as such:

```
tomcatRunWar {
    dependsOn 'build_notest'
    webApp = file('build/dist/iC.war')
}
```

**Comment by edimusrex** [comment]
That did the trick.  Thank you for your help

**Comment by bmuschko** [comment]
Sure thing.
