### ISSUE TITLE
Acessing environment variables with the plugin

### ISSUE THREAD

**Issue by bruno-lopes** [bmuschko/gradle-tomcat-plugin#193]
Hello everybody.

This is a very great plugin. But now, I'm trying to understand how to set environment variables and use them within my code with System.getenv("$VARIABLE_NAME").

In Tomcat, I'm able to do this using setenv.sh or setenv.bat files. Is it possible to do something like this in this plugin? Thanks in advance.

**Comment by bmuschko** [comment]
As mentioned in the README file:

> Gradle starts the embedded container in the same JVM. Currently, the container cannot be forked as a separate process. 

For that reason you cannot set environment variables or you have to set them for the Gradle process.
