### ISSUE TITLE
How to run the Tomcat server at http://localhost:8080 instead of http://localhost:8080/ProjectName?

### ISSUE THREAD

**Issue by nth347** [bmuschko/gradle-tomcat-plugin#197]
After setting everything for the plugin, I run the Tomcat server by typing "gradle tomcatRun", the server will run at http://localhost:8080/ProjectName. How can I run the Tomcat server at http://localhost:8080?

**Comment by bmuschko** [comment]
Set the context path to root via `tomcat. tomcat = '/'`.

**Comment by bmuschko** [comment]
Question was answered.
