### ISSUE TITLE
2.6 Release

### ISSUE THREAD

**Issue by cwrs** [bmuschko/gradle-tomcat-plugin#201]
Hi,

I just ran into the gradle 7 issues you already fixed. Are there any plans to release the 2.6 version soon? Or are there any issues left I could try to help with?

Thanks a lot for your great work!

Christian

**Comment by bmuschko** [comment]
I'll try to get to it soon. It's just a matter of time and priorities. As you might have read in the README file, I am looking for a new maintainer of the plugin.

**Comment by bmuschko** [comment]
Released. I think this should work now.

**Comment by cwrs** [comment]
Thanks a lot!
