### ISSUE TITLE
Add support for compiling the Java source obtained by the JSPs

### ISSUE THREAD

**Issue by mauromol** [bmuschko/gradle-tomcat-plugin#26]
Hi there,
your Tomcat plugin is great! I could enhance my Gradle project to translate JSPs to Java source files within minutes.

However, now I'm missing the next (natural?) step: to compile that source code into bytecode, so that I can be sure that my JSPs are correct.

Is there any easy way to do that even right now? Or can your plugin be enhanced to do that?

Thanks in advance.

**Comment by bmuschko** [comment]
Closing as issue got no traction.
