### ISSUE TITLE
Create facility for adding external directories to the runtime classpath

### ISSUE THREAD

**Issue by williewheeler** [bmuschko/gradle-tomcat-plugin#41]
Tomcat and Jetty both support the ability to add directories, external to the WAR, to their runtime classpath. This allows us to adopt the best practice of building the WAR once and adapting it to environments through environment-specific configuration.

See stackoverflow.com/questions/15130617/how-can-i-use-externalized-configuration-files-with-the-gradle-tomcat-plugin/15138491 for more information.

I was able to find a workaround that involves adding the external directory to the entire build script, which is fine by me, but probably the Tomcat plugin ought to support some way to target the plugin specifically.

Thanks for the help and for the useful plugin.

**Comment by tommyschnabel** [comment]
+1

**Comment by bmuschko** [comment]
Did you try using [AbstractTomcatRun.additionalRuntimeJars](http://bmuschko.github.io/gradle-tomcat-plugin/docs/groovydoc/com/bmuschko/gradle/tomcat/tasks/AbstractTomcatRun.html)?

**Comment by bmuschko** [comment]
This has always worked properly via `additionalRuntimeJars`. My first code example in Stackoverflow was incorrect though. It should have been that:

    [tomcatRun, tomcatRunWar].each { it.additionalRuntimeJars << file("/path/to/config/files") }

In version 2.2.1 of the plugin the property has been renamed to `additionalRuntimeResources` to better describe its intent. For more information see FAQ of the plugin.
