### ISSUE TITLE
Setting additional jvmArgs in config

### ISSUE THREAD

**Issue by zigarn** [bmuschko/gradle-tomcat-plugin#47]
I would like to add arguments (and not only properties) to Tomcat but with dynamic values (therefore I can't use GRADLE_OPTS).
For example: set the debug port dynamically.

It's a mix of issue #33 and documentation question 'How do I remote debug my Tomcat started up by the plugin?'

**Comment by sunxien** [comment]
Hi bmuschko, I am doing a job about how to use your gradle-tomcat-plugin integrate with spring-loaded.jar to support hot deploy.And I found two issues about your gradle-tomcat-plugin.The first issue:
This plugin is not support hot swap(or hot deploy).I start two terminal, I run <"gradle tomcatRun"> in the first terminal, I update some java files and run <"gradle compileJava"> in the other terminal, but I don't found Context reloaded.... The second issue is that this plugin may occur port has already be used when I specify the arguments in the gradle.properties like: 
-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
if I run <"gradle clean build"> and then run <"gradle tomcatRun">, the port 5005 has already been used.I found a solution link: https://www.timroes.de/2014/06/22/using-gradle-to-debug-tomcat/
Response to me ASAP, Eric Sun From China.
