### ISSUE TITLE
Tomcat plugin should fork

### ISSUE THREAD

**Issue by matthauck** [bmuschko/gradle-tomcat-plugin#58]
I am becoming more convinced that the tomcat plugin should fork instead of running in a sub-classloader. There are some problems of state that the classloader solution does not appear to address...

For example, in my webapp, I am calling `org.slf4j.bridge.SLF4JBridgeHandler.removeHandlersForRootLogger()` on startup to make sure all jul logging goes through `org.slf4j.bridge.SLF4JBridgeHandler.install()`. I am also using gradle in it's daemon mode, so that this static jul call removes it for all jul logging -- including gradle's own. This results in the following the next time I try to run tomcatRunWar:

```
Caused by: java.lang.ClassCircularityError: java/util/logging/LogRecord
```

If I stop the gradle daemon and start it again, then it works the first time, and then fail again every subsequent time until I stop the daemon again. (In fact, even `gradle assemble` on the gradle-tomcat-plugin itself fails until i restart the gradle daemon). 

It seems like static things like this would be set at the JVM level regardless of classloader, and that the best solution would be to fork on tomcatRun / tomcatRunWar to avoid all persistent static state between the two. It would also avoid gradle's classpath seeping into the webapp's classpath...

Is there something I'm missing here about the classloader setup? Or is forking the best way to go? If I get it to fork properly, would you be interested in merging that change?

**Comment by bmuschko** [comment]
Closing as issue got no traction.
