### ISSUE TITLE
keystoreType Setting.

### ISSUE THREAD

**Issue by FarooqKhan** [bmuschko/gradle-tomcat-plugin#71]
Seems like there is no way to set the keystoreType in case we want to use "pkcs12" keystore. So we are forced to use only a JKS keystore.

Same would happen for truststoreType as well if someone wanted to use a non default type.

Also it will be good to have the ability to specify the keyAlias. Else our keystore's first entry has to be one we want to use.

**Comment by bmuschko** [comment]
Closing as issue got no traction.
