### ISSUE TITLE
Tomcat 8 support.

### ISSUE THREAD

**Issue by bura** [bmuschko/gradle-tomcat-plugin#73]
It seems that Tomcat server interface in Tomcat 8 was changed. With 8.0.0-RC5 version I have an error:

groovy.lang.MissingPropertyException: No such property: defaultRealm for class: org.apache.catalina.startup.Tomcat

**Comment by magx2** [comment]
So does this plugin works with Tomcat8?

**Comment by bmuschko** [comment]
@magx2 We have an initial implementation which is fairly untested. If you use the latest version of the plugin, you'll be able to try it out. I didn't spend much time writing any validation for it. It might work, it might not work.

**Comment by bura** [comment]
Unfortunately, I haven't found enough time to engage with taglibs problem. Sorry guys :(

**Comment by tinobino** [comment]
There seems to be an issue with basic authentication as well.
The same configuration I'm using with Tomcat 7.0.59 isn't working on 8.0.8.
The basic authentication form shows up but it does not grant me access to secured resource.

**Comment by bmuschko** [comment]
@tinobino I am not surprised. The Tomcat 8 implementation is not ready to be used from my perspective. Contributions welcome!

**Comment by shauvik** [comment]
Thanks for your tomcat plugin. I used it for the last few months.

But I just switched to https://github.com/akhikhl/gretty
It supports tomcat 8 seamlessly and has pretty good documentation.

**Comment by billforward-alex** [comment]
> At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.

I get this message even when I deploy a war directly to standalone TomCat 8 _without_ the Gradle TomCat plugin.

I believe it is perfectly normal behaviour of TomCat 8, and not a symptom of any problem with this plugin.

**Comment by cdx-grillo** [comment]
Just confirming, no tomcat 8 support for this plugin yet?  I was attempting to use tomcat 8.5.x

**Comment by bmuschko** [comment]
@billforward-alex Thanks for looking into this. I updated the documentation to show that Tomcat 8 is supported by the plugin.
