### ISSUE TITLE
Reloadable isnt working with tomcat7

### ISSUE THREAD

**Issue by nspessot** [bmuschko/gradle-tomcat-plugin#81]
Hi,
I have set up gradle tomcat plugin to my project, I followed this tutorial to made it works but for some reason after modifying a java class and running gradle compileJava tomcat does not reload. I am using Spring tool suite as my IDE, but I execute gradle task using windows command line.

Here is my build.gradle file:

apply plugin: 'war'
apply plugin: 'tomcat'
apply plugin: 'java'
apply plugin: 'propdeps'
apply plugin: 'propdeps-maven'
apply plugin: 'propdeps-idea'
apply plugin: 'propdeps-eclipse'
apply plugin: 'eclipse'
apply plugin: 'idea'

buildscript {
  repositories {
    mavenCentral()
    maven {
      url "http://download.java.net/maven/2"
    }
    maven { url 'http://repo.spring.io/plugins-release' }
    jcenter()
  }

  dependencies {
    classpath 'org.gradle.api.plugins:gradle-tomcat-plugin:1.0'
    classpath 'org.springframework.build.gradle:propdeps-plugin:0.0.1'
  }
}

repositories {
    mavenCentral()
    maven { 
        url 'http://repo.spring.io/milestone/'
    }
    maven { 
        url 'http://www.hibernatespatial.org/repository'
    }
    maven { 
        url 'http://download.osgeo.org/webdav/geotools'
    }
}

jar {
    baseName = 'location-backend'
    version =  '0.1.0'
}

repositories {
    mavenCentral()
}

dependencies {

```
def tomcatVersion = '7.0.42'
tomcat "org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}",
        "org.apache.tomcat.embed:tomcat-embed-logging-juli:${tomcatVersion}"
tomcat("org.apache.tomcat.embed:tomcat-embed-jasper:${tomcatVersion}") {
  exclude group: 'org.eclipse.jdt.core.compiler', module: 'ecj'
}

providedCompile 'javax.servlet:javax.servlet-api:3.1.0',
                'javax.servlet:jsp-api:2.0'
```

}

[tomcatRun, tomcatRunWar, tomcatStop]_.stopPort = 8081
[tomcatRun, tomcatStop]_.stopKey = 'stopKey'

tomcatRun {
    httpPort = 8080
    httpsPort = 8443
    enableSSL = true
    reloadable = true
}

task wrapper(type: Wrapper) {
    gradleVersion = '1.9'
}

tomcatRunWar.contextPath = ''

**Comment by firesh** [comment]
Is there any update on this issue. I have same problem which reloadable is not working. I have to go back with Jetty for hot code deployment.

**Comment by bmuschko** [comment]
@firesh No update. I am waiting for external contributions for this. Want to look into it?

**Comment by chenrui333** [comment]
Any update on this issue?

**Comment by bmuschko** [comment]
Closing as issue got no traction.
