### ISSUE TITLE
remote debug is not working

### ISSUE THREAD

**Issue by xfs** [bmuschko/gradle-tomcat-plugin#93]
I config the remote debug with the FAQ,when run tomcatRun ,no info print.and can't debug.

I use eclipse and gradle 1.11.
can help me?thanks

**Comment by tonsV2** [comment]
I'm using intellij and so does several of my colleagues... Neither of us can get it working.

The following message pops up:
Error running Run Tomcat Server: Unable to open debugger port (127.0.0.1:34981): java.net.SocketException "Socket closed"

I've added the string below to the various gradle and gradlew files, run configurations and what not... Still not working. 

"-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"

Any clues? Using version 2016.2.5 btw.
