### ISSUE TITLE
Java 8 support

### ISSUE THREAD

**Issue by dstroyrofworlds** [bmuschko/gradle-tomcat-plugin#95]
Not sure if plugin already works with Java 8.

I get this error when trying to execute tomcatRun:

java.lang.ClassNotFoundException: com.ibm.crypto.tools.KeyTool
from AbstractTomcatRun.groovy:438

**Comment by gagandeepchhabda12305** [comment]
Hi All,

I need to generate an SSL certificate for my Grails application and I am facing the following issue:
|Creating SSL Certificate...
Error |
Exception in thread "main" 
Error |
java.lang.ClassNotFoundException: com.ibm.crypto.tools.KeyTool

I am using Java 8, Grails 2.4.4 and Tomcat 7.0.55 and I tried the fix suggested for replacing the code of TomcatServer.groovy but it didn't work for me, can someone please help me in the same.

Thanks

**Comment by gagandeepchhabda12305** [comment]
Hi @bmuschko, the tomcat version installed in my grails is same : 7.0.55. But still I am facing this issue.

**Comment by bmuschko** [comment]
@gagandeepchhabda12305 Maybe my comment wasn't clear before. Grails is not using this plugin. They implemented their own integration with Tomcat. You'll have to ask them to fix it.
