### ISSUE TITLE
customizing WEB-INF and META-INF for exploded WAR with tomcatRun

### ISSUE THREAD

**Issue by chronodm** [bmuschko/gradle-tomcat-plugin#97]
I'm trying to port a webapp with a heavily customized ant build to gradle, and among other things it requires
1. that certain resource files be copied/moved to the WEB-INF directory
2. that certain files from the WEB-INF directory be copied to the META-INF directory, with filtering

With the war plugin, I'm able to do something along the lines of:

```
war {
  webInf {
    from fileTree('src/main/java').files
    include "${mypattern}"
  }
  metaInf {
    from("src/main/webapp/WEB-INF")
    include "${otherpattern}"
    filter { ... }
  }
}
```

For the tomcatRun task, I can more or less duplicate this behavior by creating copy tasks that put the resources into `src/main/webapp/WEB-INF/` and the filtered file into `src/main/webapp/META-INF` -- but note the `src`. Basically I have to pollute my source tree to get this to work.

Is there any way to add files at runtime to the exploded WAR's WEB-INF and META-INF without putting them in the source directory?

**Comment by tommyschnabel** [comment]
+1 on this

**Comment by bmuschko** [comment]
Closing as issue got no traction.
